### ISSUE TITLE
Bug: mqtt connection loop in v2.1.0

### ISSUE THREAD

**Issue by DanielTerletzkiy** [hass-agent/HASS.Agent#171]
**Describe the bug**
after updating to v2.1.0 the MQTT tries to connect, connects successfully for like 1sec and tries to reconnect over and over again

**To Reproduce**
1. install v2.1.0
2. do the config migration in the installer
3. MQTT is looping

**Expected behavior**
mqtt should connect and stay connected

**Screenshots**
_homescreen mqtt going from "running" to "connecting" quickly_

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 24H2 Build 26100.1591
 - Windows' UI language: 
 - HASS.Agent version: 2.1.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
after a while it connected for 2 whole minutes and started looping again

**Logs**
```
2024-09-28 15:36:00.601 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:00.652 +02:00 [INF] [NOTIFIER] Ready
2024-09-28 15:36:01.254 +02:00 [INF] [LOCALAPI] listening on port 5115
2024-09-28 15:36:02.084 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:02.628 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:02.630 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:03.107 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:03.298 +02:00 [INF] [HASS_API] Home Assistant version: 2024.9.3
2024-09-28 15:36:03.537 +02:00 [INF] [HASS_API] System connected with https://homeassistant.local:8123/
2024-09-28 15:36:03.638 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:03.639 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:04.117 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:04.666 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:04.667 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:05.118 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:05.684 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:05.684 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:06.131 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:06.701 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:06.702 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:07.145 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:07.713 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:07.714 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:08.159 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:08.725 +02:00 [INF] [MQTT] Connected
2024-09-28 15:36:08.726 +02:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-28 15:36:09.174 +02:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-28 15:36:09.739 +02:00 [INF] [MQTT] Connected

```

**Comment by amadeo-alex** [comment]
Could you please enable extended logging and then paste the logs here? 
I assume the only "variable" is the HASS.Agent update, no MQTT broker updates also etc?
Which MQTT broker are you using?

**Comment by matheusvellone** [comment]
It happened

```
2024-09-30 09:41:36.188 -03:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Client.MqttClient.TrySendKeepAliveMessages(CancellationToken cancellationToken)
2024-09-30 09:41:36.188 -03:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:36.188 -03:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at MQTTnet.Internal.AsyncQueue`1.TryDequeueAsync(CancellationToken cancellationToken)
2024-09-30 09:41:36.189 -03:00 [FTL] [PROGRAM] FirstChanceException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttPacket packet, CancellationToken cancellationToken)
2024-09-30 09:41:36.189 -03:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:36.189 -03:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:36.189 -03:00 [FTL] [PROGRAM] FirstChanceException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttPacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.PublishAtMostOnce(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2024-09-30 09:41:36.189 -03:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:36.189 -03:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:36.189 -03:00 [FTL] [PROGRAM] FirstChanceException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttPacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.PublishAtMostOnce(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
   at HASS.Agent.MQTT.MqttManager.AnnounceAvailabilityAsync(Boolean offline) in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent\MQTT\MqttManager.cs:line 541
2024-09-30 09:41:36.189 -03:00 [FTL] [MQTT] Error while announcing availability: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttPacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.PublishAtMostOnce(MqttPublishPacket publishPacket, CancellationToken cancellationToken)
   at HASS.Agent.MQTT.MqttManager.AnnounceAvailabilityAsync(Boolean offline) in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent\MQTT\MqttManager.cs:line 541
2024-09-30 09:41:36.190 -03:00 [ERR] [NET] [ConnectionReset] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:36.190 -03:00 [ERR] [NET] [MqttCommunicationException.SocketException] An existing connection was forcibly closed by the remote host.
2024-09-30 09:41:48.387 -03:00 [INF] [MEDIA] Now playing: Mamonas Assassinas - 1406
2024-09-30 09:41:48.391 -03:00 [INF] [MEDIA] New state: Paused
2024-09-30 09:41:54.536 -03:00 [WRN] [MQTT] Not connected, message dropped (won't report again for 5 minutes)
2024-09-30 09:41:57.779 -03:00 [FTL] [NET] [TimedOut] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2024-09-30 09:41:57.779 -03:00 [FTL] [NET] FirstChancemqttCommunicationException: The operation has timed out.
MQTTnet.Exceptions.MqttCommunicationTimedOutException: The operation has timed out.
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2024-09-30 09:42:36.344 -03:00 [WRN] [MQTT] Disconnected: UnspecifiedError
2024-09-30 09:42:57.884 -03:00 [ERR] [MQTT] Error while connecting: Connection timed out
2024-09-30 09:42:57.923 -03:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2024-09-30 09:43:05.954 -03:00 [INF] [MQTT] Connected
```

**Comment by amadeo-alex** [comment]
> I'm getting this loop randomly too.
> 
> Using Mosquitto docker image as a broker
> 
> > What is the grace period that you have configured?
> 
> I don't know. I guess the default one
> 
> When I restarted the agent to enable extendes logs, MQTT took a while to connect and then failed. Right after failing, it connected
> Logs from the start until it connected successfully (i guess)
> 
> After this, I've been waiting for the conection failed notification and it didn't poped up, but I've found this logs which might be helpful
> Logs
> 
> If/when it fails I will post logs here

Thank you for pitching and and providing the logs!
The "System.ObjectDisposedException: Cannot access a disposed object." gives me a bit of a hint but I'll need to find a way to reproduce it as then fixing it will be much much easier (I haven't encountered this during the development)

Some additional questions if I may:
- do you use username/password for MQTT connection?
- do you use certificates for MQTT connection?
- I assume as with Daniel, issue was not present on 2.0.1 (or betas?) and appeared with 2.1.0?

**Comment by DanielTerletzkiy** [comment]
i use the home assistant mosquitto broker addon with username+password, without certificates
currently don't use any certificates and never had with hass-agent

**Comment by matheusvellone** [comment]
username + password too and without certificates

I updated from the legacy app to this one recently, but I remember updating to 2.1.0 after. I don't recall receiving this notifications before the update (but there is a chance I'm confused sorry)

**Comment by matheusvellone** [comment]
Looking at the logs right now I can see 532 occurrences of `System.ObjectDisposedException: Cannot access a disposed object.`, but I dindn't receive 532 notifications along the day.

Here it is all different occurrences with the stack traces for the error you mentioned

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttPacket packet, CancellationToken cancellationToken)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.<ThrowIfDisposed>g__ThrowObjectDisposedException|63_0()
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.WriteAsync(ArraySegment`1 buffer, Boolean isEndOfPacket, CancellationToken cancellationToken)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncLockWaiter'.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.<ThrowIfDisposed>g__ThrowObjectDisposedException|63_0()
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.<ThrowIfDisposed>g__ThrowObjectDisposedException|63_0()
```

**Comment by amadeo-alex** [comment]
Ok so, I still wasn't able to fully replicate this, by this I mean the exception regarding disposed object.
I tried to do some changes that in theory should prevent a situation where the library tries to access the MQTT client after it has been disposed from what I can see the exceptions are coming directly from library rather than HASS.Agent itself.

But before I elaborate: to have any kind o test bed - MQTT status cycling between "running" and "connecting" - I had to run two instances of HASS.Agent that had the same MQTT settings (client id).
I'd like to ask you to check the MQTT (mosquitto) logs for something like this:
![N8AtkW](https://github.com/user-attachments/assets/40911234-0579-4c75-bc66-7dee4954b1e2)
Those are the logs from where I had two instances of HASS.Agent running - if the same logs appear while you're having the issues it means that there are two instances of HASS.Agent with "same" config running at the same time - which is bad of course.

Now going back to what I tried to do, there is a test build available here - https://github.com/amadeo-alex/HASS.Agent/releases/tag/2.1.1-beta2-mqttdisposed - with the changes I mentioned at the beginning.
If possible try it (and check the MQTT logs before of course) and let me know if it changes anything.

**Comment by matheusvellone** [comment]
The day after reporting the problem it stopped giving the notification errors (i guess)

Didn't made any upgrades to any related container, but I had some manual restarts last weeks, maybe it helped making connections more stable. Now thats stable, can't reproduce it neither test the version you published 😕

**Comment by ManuVice** [comment]
I had the same problem. I have two Windows 11 users.

I have disabled "Automatic Sign-in after Update" in Settings/User and my loop was gone.

**Comment by ManuVice** [comment]
yes both users have the same mqtt config

**Comment by amadeo-alex** [comment]
@DanielTerletzkiy could you please take a look at comments above and judge if they help :D

**Comment by DanielTerletzkiy** [comment]
i didn't have this issue anymore after doing a clean installation to the latest beta version, the configuration stayed the same...

**Comment by DrR0X-glitch** [comment]
> Interesting, that would mean both of the users used the same MQTT configuration? [@DrR0X-glitch](https://github.com/DrR0X-glitch) sorry for so many pings but we'll have some reference :D Might be a good idea to add a note to MQTT docs that all installations of HASS.Agent need to use different clientid, even if those are 2 users on the same machine.

I seem to have noticed the connection loop as well, only one user though, restarting pc fixed it and has never happened since, so a little bit confused honestly.
