### ISSUE TITLE
Calls device_registry.async_update_device from a thread other than the event loop

### ISSUE THREAD

**Issue by caohuongls** [hass-agent/HASS.Agent#184]
2024-10-18 14:34:31.366 ERROR (SyncWorker_7) [homeassistant.util.logging] Exception in updated when handling msg on 'hass.agent/devices/LABO_COMPUTER': '{"serial_number":"b4c93d21-7f28-4a0d-b1cf-922a17d54487","device":{"identifiers":"hass.agent-LABO_COMPUTER","manufacturer":"HASS.Agent Team","model":"Microsoft Windows NT 10.0.22000.0","name":"LABO_COMPUTER","sw_version":"2.1.0"},"apis":{"notifications":true,"media_player":true}}'
Traceback (most recent call last):
File "/config/custom_components/hass_agent/__init__.py", line 144, in updated
update_device_info(hass, entry, payload)
File "/config/custom_components/hass_agent/__init__.py", line 29, in update_device_info
device_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 834, in async_get_or_create
device = self.async_update_device(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1066, in async_update_device
self.hass.verify_event_loop_thread("device_registry.async_update_device")
File "/usr/src/homeassistant/homeassistant/core.py", line 462, in verify_event_loop_thread
frame.report_non_thread_safe_operation(what)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 229, in report_non_thread_safe_operation
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 163, in report
_report_integration(what, integration_frame, level, error_if_integration)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 201, in _report_integration
raise RuntimeError(
RuntimeError: Detected that custom integration 'hass_agent' calls device_registry.async_update_device from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#device_registryasync_update_device at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(. Please report it to the author of the 'hass_agent' custom integration.
2024-10-18 14:34:31.368 ERROR (SyncWorker_3) [homeassistant.util.logging] Exception in updated when handling msg on 'hass.agent/devices/HASS_SERVER': '{"serial_number":"c52c348a-53f9-4588-930f-8397d608e6f0","device":{"identifiers":"hass.agent-HASS_SERVER","manufacturer":"HASS.Agent Team","model":"Microsoft Windows NT 10.0.22631.0","name":"HASS_SERVER","sw_version":"2.1.0"},"apis":{"notifications":true,"media_player":true}}'
Traceback (most recent call last):
File "/config/custom_components/hass_agent/__init__.py", line 144, in updated
update_device_info(hass, entry, payload)
File "/config/custom_components/hass_agent/__init__.py", line 29, in update_device_info
device_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 834, in async_get_or_create
device = self.async_update_device(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1066, in async_update_device
self.hass.verify_event_loop_thread("device_registry.async_update_device")
File "/usr/src/homeassistant/homeassistant/core.py", line 462, in verify_event_loop_thread
frame.report_non_thread_safe_operation(what)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 229, in report_non_thread_safe_operation
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 163, in report
_report_integration(what, integration_frame, level, error_if_integration)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 201, in _report_integration
raise RuntimeError(
RuntimeError: Detected that custom integration 'hass_agent' calls device_registry.async_update_device from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#device_registryasync_update_device at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(. Please report it to the author of the 'hass_agent' custom integration.

**Comment by amadeo-alex** [comment]
https://github.com/hass-agent/HASS.Agent-Integration/issues/2
https://github.com/hass-agent/HASS.Agent-Integration?tab=readme-ov-file#installation
