### ISSUE TITLE
Notifications Fail

### ISSUE THREAD

**Issue by jtst1** [hass-agent/HASS.Agent#203]
Not sure if this is the right place for this, but I cannot get notifications to work with the HASS Agent, even the local test one in the settings. When I look at the logs this is what I get

2024-12-21 17:18:24.164 -05:00 [INF] [NOTIFIER] Attempting to show test notification ..
2024-12-21 17:18:24.181 -05:00 [INF] [NOTIFIER] Test notification attempt completed
2024-12-21 17:18:24.300 -05:00 [ERR] [NOTIFIER] Notification 'HASS.Agent' failed to show

Notifications are turned on in windows settings for HASS Agent, do not disturb is turned off, focus session not turned on, other applications can send notifications fine. If this is the wrong place to ask for help please let me know where I should. Thanks.

**Comment by amadeo-alex** [comment]
Moved to HASS.Agent repo as the test one fails.
Could you please enable debug logging, restart HASS.Agent try to show the test notification and then post the logs?

**Comment by jtst1** [comment]
2024-12-24 16:53:58.861 -05:00 [INF] [MAIN] HASS.Agent version: 2.1.0
2024-12-24 16:53:58.867 -05:00 [INF] [SETTINGS] Config storage path: C:\Users\Jtst1\AppData\Local\HASS.Agent\Client\config
2024-12-24 16:53:58.947 -05:00 [INF] [SETTINGS] Configuration loaded
2024-12-24 16:53:58.950 -05:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2024-12-24 16:53:59.364 -05:00 [INF] [RADIOMGR] Radio management permission granted
2024-12-24 16:53:59.381 -05:00 [INF] [RADIOMGR] Ready
2024-12-24 16:54:01.408 -05:00 [INF] [INTERNALSENSORS] Ready
2024-12-24 16:54:02.093 -05:00 [INF] [VIRTDESKT] Virtual Desktop Manager initialized
2024-12-24 16:54:02.356 -05:00 [INF] [AUDIOMGR] initialized
2024-12-24 16:54:02.366 -05:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2024-12-24 16:54:02.393 -05:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2024-12-24 16:54:02.460 -05:00 [INF] [SETTINGS_SENSORS] Loaded 1 entities
2024-12-24 16:54:02.467 -05:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2024-12-24 16:54:02.513 -05:00 [INF] [LOCALAPI] Initializing ..
2024-12-24 16:54:02.513 -05:00 [INF] [LOCALAPI] Ignoring certificate errors for images
2024-12-24 16:54:02.599 -05:00 [INF] [MQTT] Identifying as device: Desktop
2024-12-24 16:54:02.607 -05:00 [INF] [MQTT] Connecting ..
2024-12-24 16:54:02.718 -05:00 [INF] [HASS_API] Home Assistant version: 2024.12.5
2024-12-24 16:54:02.860 -05:00 [INF] [HASS_API] System connected with http://hassio:8123
2024-12-24 16:54:03.260 -05:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent Satellite Service\Service\
2024-12-24 16:54:03.265 -05:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: Unsupported
2024-12-24 16:54:03.269 -05:00 [INF] [NOTIFIER] Ready
2024-12-24 16:54:03.296 -05:00 [INF] [MEDIA] Ready
2024-12-24 16:54:03.333 -05:00 [INF] [LOCALAPI] listening on port 5115
2024-12-24 16:54:03.690 -05:00 [INF] [MQTT] Connected
2024-12-24 16:54:05.257 -05:00 [INF] [MQTT] Initial registration completed
2024-12-24 16:54:07.751 -05:00 [INF] [SETTINGS] Configuration stored
2024-12-24 16:54:09.759 -05:00 [INF] [SYSTEM] Application shutting down
2024-12-24 16:54:09.764 -05:00 [INF] [MQTT] Disconnected
2024-12-24 16:54:09.775 -05:00 [INF] [SYSTEM] Application shutdown complete
2024-12-24 16:54:11.694 -05:00 [INF] [MAIN] HASS.Agent version: 2.1.0
2024-12-24 16:54:11.697 -05:00 [INF] [MAIN] Extended logging enabled
2024-12-24 16:54:11.701 -05:00 [INF] [SETTINGS] Config storage path: C:\Users\Jtst1\AppData\Local\HASS.Agent\Client\config
2024-12-24 16:54:11.784 -05:00 [INF] [SETTINGS] Configuration loaded
2024-12-24 16:54:11.787 -05:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2024-12-24 16:54:11.938 -05:00 [DBG] [RADIOMGR] Initialization started
2024-12-24 16:54:11.983 -05:00 [INF] [RADIOMGR] Radio management permission granted
2024-12-24 16:54:11.983 -05:00 [DBG] [RADIOMGR] Enumerating proximity/NFC devices
2024-12-24 16:54:11.994 -05:00 [INF] [RADIOMGR] Ready
2024-12-24 16:54:14.035 -05:00 [INF] [INTERNALSENSORS] Ready
2024-12-24 16:54:14.574 -05:00 [INF] [VIRTDESKT] Virtual Desktop Manager initialized
2024-12-24 16:54:14.574 -05:00 [DBG] [AUDIOMGR] initializing
2024-12-24 16:54:14.799 -05:00 [INF] [AUDIOMGR] initialized
2024-12-24 16:54:14.808 -05:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2024-12-24 16:54:14.828 -05:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2024-12-24 16:54:14.889 -05:00 [INF] [SETTINGS_SENSORS] Loaded 1 entities
2024-12-24 16:54:14.894 -05:00 [INF] [LOCALAPI] Initializing ..
2024-12-24 16:54:14.894 -05:00 [INF] [LOCALAPI] Ignoring certificate errors for images
2024-12-24 16:54:14.894 -05:00 [INF] [MQTT] Identifying as device: Desktop
2024-12-24 16:54:14.896 -05:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2024-12-24 16:54:14.900 -05:00 [INF] [MQTT] Connecting ..
2024-12-24 16:54:14.907 -05:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent Satellite Service\Service\
2024-12-24 16:54:14.911 -05:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: Unsupported
2024-12-24 16:54:14.914 -05:00 [INF] [NOTIFIER] Ready
2024-12-24 16:54:14.937 -05:00 [INF] [MEDIA] Ready
2024-12-24 16:54:14.945 -05:00 [WRN] [MEDIA] No MediaSession active
2024-12-24 16:54:14.952 -05:00 [INF] [MQTT] Connected
2024-12-24 16:54:14.953 -05:00 [INF] [HASS_API] Home Assistant version: 2024.12.5
2024-12-24 16:54:15.089 -05:00 [INF] [HASS_API] System connected with http://hassio:8123
2024-12-24 16:54:15.143 -05:00 [INF] [LOCALAPI] listening on port 5115
2024-12-24 16:54:16.919 -05:00 [INF] [MQTT] Initial registration completed
2024-12-24 16:54:21.113 -05:00 [INF] [NOTIFIER] Attempting to show test notification ..
2024-12-24 16:54:21.126 -05:00 [INF] [NOTIFIER] Test notification attempt completed
2024-12-24 16:54:21.242 -05:00 [ERR] [NOTIFIER] Notification 'HASS.Agent' failed to show

**Comment by amadeo-alex** [comment]
> 2024-12-24 16:54:14.911 -05:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: Unsupported

What version of window you're using?

**Comment by jtst1** [comment]
Windows 11 Version 23H2 Build 22631.4602

**Comment by amadeo-alex** [comment]
https://github.com/amadeo-alex/HASS.Agent/releases/tag/2.1.1-beta3-test-sdkupdate
I don't have high hopes of this being the fix but it's worth a try.
Please make backup of the configuration before trying.

**Comment by virtualJonesie** [comment]
I have the same issue with the same 3 lines in the log file. Windows 10 22H2
```

2025-01-27 14:47:04.080 -05:00 [INF] [NOTIFIER] Attempting to show test notification ..
2025-01-27 14:47:04.096 -05:00 [INF] [NOTIFIER] Test notification attempt completed
2025-01-27 14:47:04.325 -05:00 [ERR] [NOTIFIER] Notification 'HASS.Agent' failed to show
```

**Comment by fragolinux** [comment]
same here... windows 11, build 26100.2894, ha 2025.1.4, hass.agent 2.1.1-beta3

```
2025-02-02 12:14:29.812 +01:00 [INF] [SETTINGS] Configuration stored
2025-02-02 12:14:32.606 +01:00 [INF] [SYSTEM] Application shutting down
2025-02-02 12:14:32.612 +01:00 [FTL] [PROGRAM] FirstChanceException: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2025-02-02 12:14:32.617 +01:00 [FTL] [PROGRAM] FirstChanceException: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MQTTnet.Internal.BlockingQueue`1.PeekAndWait(CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.PublishQueuedMessagesAsync(CancellationToken cancellationToken)
2025-02-02 12:14:32.619 +01:00 [INF] [MQTT] Disconnected
2025-02-02 12:14:32.688 +01:00 [INF] [SYSTEM] Application shutdown complete
2025-02-02 12:14:35.191 +01:00 [INF] [MAIN] HASS.Agent version: 2.1.1-beta3
2025-02-02 12:14:35.197 +01:00 [INF] [MAIN] Extended logging enabled
2025-02-02 12:14:35.204 +01:00 [INF] [SETTINGS] Config storage path: C:\Users\mrshark\AppData\Local\HASS.Agent\Client\config
2025-02-02 12:14:35.382 +01:00 [INF] [SETTINGS] Configuration loaded
2025-02-02 12:14:35.386 +01:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2025-02-02 12:14:35.685 +01:00 [DBG] [RADIOMGR] Initialization started
2025-02-02 12:14:35.779 +01:00 [INF] [RADIOMGR] Radio management permission granted
2025-02-02 12:14:35.779 +01:00 [DBG] [RADIOMGR] Enumerating proximity/NFC devices
2025-02-02 12:14:35.806 +01:00 [INF] [RADIOMGR] Ready
2025-02-02 12:14:37.891 +01:00 [INF] [INTERNALSENSORS] Ready
2025-02-02 12:14:38.424 +01:00 [INF] [VIRTDESKT] Virtual Desktop Manager initialized
2025-02-02 12:14:38.425 +01:00 [DBG] [AUDIOMGR] initializing
2025-02-02 12:14:38.703 +01:00 [INF] [AUDIOMGR] initialized
2025-02-02 12:14:38.723 +01:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2025-02-02 12:14:38.725 +01:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2025-02-02 12:14:44.091 +01:00 [INF] [SETTINGS_SENSORS] Loaded 6 entities
2025-02-02 12:14:44.098 +01:00 [INF] [LOCALAPI] Disabled
2025-02-02 12:14:44.099 +01:00 [INF] [MQTT] Identifying as device: PICCIUNAZZU
2025-02-02 12:14:44.102 +01:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2025-02-02 12:14:44.115 +01:00 [INF] [MQTT] Connecting ..
2025-02-02 12:14:44.131 +01:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent Satellite Service\Service\
2025-02-02 12:14:44.177 +01:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: Unsupported
2025-02-02 12:14:44.179 +01:00 [INF] [MEDIA] Ready
2025-02-02 12:14:44.184 +01:00 [INF] [NOTIFIER] Ready
2025-02-02 12:14:44.211 +01:00 [INF] [MEDIA] Now playing: Makers at Work - I MIGLIORI 3 Banchi Sega per la Falegnameria Fai da te
2025-02-02 12:14:44.223 +01:00 [INF] [MQTT] Connected
2025-02-02 12:14:44.258 +01:00 [INF] [HASS_API] Home Assistant version: 2025.1.4
2025-02-02 12:14:44.285 +01:00 [INF] [MEDIA] New state: Paused
2025-02-02 12:14:44.593 +01:00 [INF] [HASS_API] System connected with http://192.168.1.57:8123
2025-02-02 12:14:46.133 +01:00 [INF] [MQTT] Initial registration completed
2025-02-02 12:14:55.680 +01:00 [INF] [NOTIFIER] Attempting to show test notification ..
2025-02-02 12:14:55.703 +01:00 [INF] [NOTIFIER] Test notification attempt completed
2025-02-02 12:14:56.151 +01:00 [ERR] [NOTIFIER] Notification 'HASS.Agent' failed to show
2025-02-02 12:15:14.216 +01:00 [ERR] [NOTIFIER] Notification 'Home Assistant' failed to show

```

**Comment by virtualJonesie** [comment]
Mine is not working again. Same log entries.

I have double-checked Windows 10 Notification settings. HASS Agent is there and enabled.

**Comment by TheDruidsKeeper** [comment]
I'm using a fresh install of latest home assistant, HACS, & HASS. It looks like I'm running into this same issue on my Windows 11 PC being unable to receive notifications. The local test notification _does_ work for me though. The PC shows up in HA, along with any Sensors & Commands that I configure, but I do not have the option to send notifications. I've reinstalled the server integration & agent multiple times, and rebooted devices, but haven't been able to get my PC to appear as a notifiable target.

### Versions
Windows 11 Pro: 24H2 (26100.3194)
HASS.Agent: 2.1.1
HASS.Agent 2 Integration: 2.1.1
HA Core: 2025.2.4


### HASS Agent Logs
> 2025-02-18 15:16:41.649 -07:00 [INF] [MAIN] HASS.Agent version: 2.1.1
2025-02-18 15:16:41.654 -07:00 [INF] [MAIN] Extended logging enabled
2025-02-18 15:16:41.659 -07:00 [INF] [SETTINGS] Config storage path: C:\Users\thedr\AppData\Local\HASS.Agent\Client\config
2025-02-18 15:16:41.774 -07:00 [INF] [SETTINGS] Configuration loaded
2025-02-18 15:16:41.778 -07:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2025-02-18 15:16:42.446 -07:00 [DBG] [RADIOMGR] Initialization started
2025-02-18 15:16:42.518 -07:00 [INF] [RADIOMGR] Radio management permission granted
2025-02-18 15:16:42.518 -07:00 [DBG] [RADIOMGR] Enumerating proximity/NFC devices
2025-02-18 15:16:42.535 -07:00 [INF] [RADIOMGR] Ready
2025-02-18 15:16:44.599 -07:00 [INF] [INTERNALSENSORS] Ready
2025-02-18 15:16:45.616 -07:00 [INF] [VIRTDESKT] Virtual Desktop Manager initialized
2025-02-18 15:16:45.617 -07:00 [DBG] [AUDIOMGR] initializing
2025-02-18 15:16:46.056 -07:00 [INF] [AUDIOMGR] initialized
2025-02-18 15:16:46.069 -07:00 [INF] [SETTINGS_QUICKACTIONS] Config not found, no entities loaded
2025-02-18 15:16:46.116 -07:00 [INF] [SETTINGS_COMMANDS] Loaded 1 entities
2025-02-18 15:16:46.122 -07:00 [INF] [SETTINGS_SENSORS] Loaded 0 entities
2025-02-18 15:16:46.196 -07:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2025-02-18 15:16:46.268 -07:00 [INF] [LOCALAPI] Disabled
2025-02-18 15:16:46.343 -07:00 [INF] [MQTT] Identifying as device: MICHAEL-PX
2025-02-18 15:16:46.397 -07:00 [INF] [MQTT] Connecting ..
2025-02-18 15:16:46.404 -07:00 [INF] [MEDIA] Disabled
2025-02-18 15:16:46.406 -07:00 [ERR] [SERVICE] Unable to retrieve install path from service, and default path not found
2025-02-18 15:16:46.459 -07:00 [INF] [MQTT] Connected
2025-02-18 15:16:46.548 -07:00 [INF] [HASS_API] Home Assistant version: 2025.2.4
2025-02-18 15:16:46.704 -07:00 [INF] [HASS_API] System connected with https://[redacted]
2025-02-18 15:16:46.782 -07:00 [INF] [NOTIFIER] Ready
2025-02-18 15:16:48.405 -07:00 [INF] [MQTT] Initial registration completed
2025-02-18 15:17:45.707 -07:00 [INF] [NOTIFIER] Attempting to show test notification ..
2025-02-18 15:17:45.722 -07:00 [INF] [NOTIFIER] Test notification attempt completed


### Home Assistant
Without any sensors or commands configured I only only see the `HASS.Agent` integration device:
![Image](https://github.com/user-attachments/assets/43b48fcf-683b-4eeb-b12e-038a03d9dafc)

As soon as I add any commands or sensors, I see a separate device via MQTT:
![Image](https://github.com/user-attachments/assets/f7a2d049-8c0c-49bc-b2fb-1cdc6ababd2e)

The HASS device cannot be used as a target for any actions or notifications. The MQTT device cannot be used as the target for any notifications, and the only actions available are from the custom commands.

**Comment by vulcanjedi** [comment]
Same here, I recently discovered use case and finally got HassAgent, worked great, decided another use case on diff PC and thought things were great but when I tried to send notification I realized didnt work, nor does the local test from config work and its Win11.

**Comment by kokobadu** [comment]
Unfortunatly same here. On Windows 11 Pro 24H2, 10.0.26100.4061. Local test failed. Notifications from other progs work well (outlook, etc). On other pc with win11 23H2 on it everything is just fine. 
Any hints?

**Comment by amadeo-alex** [comment]
I need one of those windows builds any try to narrow down the idea - I was lacking time before to do so. I have a lil more now so I'll try to find a slot for it.
