### ISSUE TITLE
Bug:MQTT Bug

### ISSUE THREAD

**Issue by flamestsui** [hass-agent/HASS.Agent#213]
![Snipaste_2024-12-31_14-19-02](https://github.com/user-attachments/assets/7e061169-87d5-4191-b04a-fa8db84de5f8)
![Snipaste_2024-12-31_14-19-23](https://github.com/user-attachments/assets/0258344b-9963-4f5d-b150-f190f40a546f)

use: homeassistant.local is ok

log:2024-12-31 14:15:23.697 +08:00 [FTL] [MQTT] Error while connecting: Error while authenticating. Connection closed.
MQTTnet.Adapter.MqttConnectingFailedException: Error while authenticating. Connection closed.
 ---> MQTTnet.Exceptions.MqttCommunicationException: Connection closed.
   at MQTTnet.Client.MqttClient.Authenticate(IMqttChannelAdapter channelAdapter, MqttClientOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Client.MqttClient.Authenticate(IMqttChannelAdapter channelAdapter, MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectInternal(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync(CancellationToken cancellationToken)
2024-12-31 14:15:23.701 +08:00 [WRN] [MQTT] Disconnected: UnspecifiedError
2024-12-31 14:17:27.847 +08:00 [INF] [HASS_API] Server recovered from failed state

**Comment by flamestsui** [comment]
use: homeassistant.local is ok
but use dsm.xxx.xxx is not ok
use python mqtt to ha is ok,but app is fail

**Comment by flamestsui** [comment]
In the settings, set it to homeassistant.local and it can be used normally.
However, if the IP is set to the domain name (the domain name points to the same point), it will not work.
The same domain name can be submitted to HA using MQTT using Python, but the App cannot.

**Comment by amadeo-alex** [comment]
Does it also work in HASS.Agent if you put plain IP in the "Broker IP Address or Hostname" field?

**Comment by flamestsui** [comment]
No way either

**Comment by amadeo-alex** [comment]
Hm, does the "homeassistant.local" resolve to the same IP address as "dsm.xxx.xxx"?
I'm trying to think what might be the issue here but the fact that it works ok with "homeassistant.local" complicates things.

**Comment by flamestsui** [comment]
@amadeo-alex 

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/31541ae7-e7e5-424a-a1ae-756f67555adc" />

**Comment by flamestsui** [comment]
<img width="685" alt="Image" src="https://github.com/user-attachments/assets/723b8ac6-36c4-45d2-a075-eef5ff3b58b0" />
That's it, my port 18313 ports to port 1883

**Comment by flamestsui** [comment]
[\[2025-01-24\] HASS.Agent_20250124.log](https://github.com/user-attachments/files/18533265/2025-01-24.HASS.Agent_20250124.log)

The logs，

**Comment by flamestsui** [comment]
@amadeo-alex 
![Image](https://github.com/user-attachments/assets/411ee1e0-4d08-490a-8af7-f2acca76361f)

![Image](https://github.com/user-attachments/assets/46168ae9-430e-4fdc-b302-5106dfb32246)

That's it, my port 18xxx ports to port 1883
I write a program in Python, the server is still dsm.iyan.vip, the port is still 18xxx and I can send mqtt information to the server


[\[2025-01-24\] HASS.Agent_20250124.log](https://github.com/user-attachments/files/18533374/2025-01-24.HASS.Agent_20250124.log)
The logs，
but Mosquitto broker logs is

2025-01-24 17:19:18: New connection from 101.207.128.132:12674 on port 1883.
2025-01-24 17:19:18: New client connected from 101.207.128.132:12674 as 29ebabcf (p2, c1, k15, u'haclient').
2025-01-24 17:19:37: Client 29ebabcf closed its connection.
2025-01-24 17:20:38: New connection from 101.207.128.132:1888 on port 1883.
2025-01-24 17:20:38: New client connected from 101.207.128.132:1888 as 29ebabcf (p2, c1, k15, u'haclient').
2025-01-24 17:20:57: Client 29ebabcf closed its connection.
2025-01-24 17:21:36: New connection from 101.207.128.132:43798 on port 1883.
2025-01-24 17:21:36: New client connected from 101.207.128.132:43798 as 29ebabcf (p2, c1, k15, u'haclient').
2025-01-24 17:21:55: Client 29ebabcf closed its connection.
2025-01-24 17:23:00: New connection from 101.207.128.132:51648 on port 1883.
2025-01-24 17:23:00: New client connected from 101.207.128.132:51648 as 29ebabcf (p2, c1, k15, u'haclient').
2025-01-24 17:23:19: Client 29ebabcf closed its connection.

**Comment by NexGen-3D-Printing** [comment]
I just upgraded to v2.1.1 from an older build, and I now have the exact same MQTT issues, it keeps disconnecting in the same pattern as above, a restart of the agent and the issue goes away, but the issue will return after time, the previous version had been running perfectly for nearly a year.
