### ISSUE TITLE
Bug: Latest HA Core update 2024.5.0 breaks notification entities.

### ISSUE THREAD

**Issue by hacshacdgacs** [hass-agent/HASS.Agent#75]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
The latest HA Core update (2024.5.0) stops hass.agent from creating any notify entities. 

**To Reproduce**
1. Update HA Core to 2024.5.0
2. When the server restarts it won't have any hass.agent notification entities.

**Expected behavior**
That the notify entities are created like normal.

**Misc info (please complete the following information):**
![image](https://github.com/hass-agent/HASS.Agent/assets/85550264/6464e32d-2eda-49ca-9dfb-e7790c12bdf0)
 - Windows' UI language: English
 - HASS.Agent version: 2.0.1

**Comment by Tomanic-glitch** [comment]
I seem to have similar issue where after HA Core update to 2024.5.0 the media player entity isn't created

Logger: homeassistant.util.logging
Source: util/logging.py:98

Exception in updated when handling msg on 'hass.agent/devices/HASS-AGENT': '{"serial_number":"b8138def-2392-47fb-9390-7f09f52ca75c","device":{"identifiers":"hass.agent-HASS-AGENT","manufacturer":"HASS.Agent Team","model":"Microsoft Windows NT 10.0.22631.0","name":"HASS-AGENT","sw_version":"2.1.0-beta1"},"apis":{"notifications":true,"media_player":true}}' Traceback (most recent call last): File "/config/custom_components/hass_agent/__init__.py", line 144, in updated update_device_info(hass, entry, payload) File "/config/custom_components/hass_agent/__init__.py", line 29, in update_device_info device_registry.async_get_or_create( File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 758, in async_get_or_create device = self.async_update_device( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 907, in async_update_device self.hass.verify_event_loop_thread("async_update_device") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'hass_agent' calls async_update_device from a thread at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(. Please report it to the author of the 'hass_agent' custom integration.

![Sceen_01-05-2024_23-56-53](https://github.com/hass-agent/HASS.Agent/assets/61036575/d52a8c7a-9c38-4407-8570-a9a6baae89d5)

**Comment by hacshacdgacs** [comment]
Can confirm my media player integration also isn't being created. Tuya-Local is also having an issue with all devices starting offline after a restart so there is a HomeAssistant change that's affected things

**Comment by Wank-ster** [comment]
I might add here that for me who has installed hass.agent for the first time while being on a 2024.5.0: 
Device pops up in auto detect and I can add/configure it but then again not a single entity or the device itself is being created.

**Comment by Protoncek** [comment]
Regarding media player: since i've had installed this agent before i did have media player, but now it's there, but it's unavailable. Going back to 2024.4 solves the problem.

**Comment by amadeo-alex** [comment]
Preface: issue regards the integration not HASS.Agent client itself - we might move this issue to integration repo at some point.

Definitely either something that we've been doing wrong from the beginning and now HA refuses to accept that or they've changed something with new release. I'll take a look with @DrR0X-glitch how to fix it.
Bad thing is that even if we do, the HACS integration that was maintained by Sam will say the same, modified one will need to be added manually to HACS as a repo before it can be installed (supposedly the approval process for HACS can take multiple months atm)

**Comment by hacshacdgacs** [comment]
> Preface: issue regards the integration not HASS.Agent client itself - we might move this issue to integration repo at some point.
> 
> Definitely either something that we've been doing wrong from the beginning and now HA refuses to accept that or they've changed something with new release. I'll take a look with @DrR0X-glitch how to fix it. Bad thing is that even if we do, the HACS integration that was maintained by Sam will say the same, modified one will need to be added manually to HACS as a repo before it can be installed (supposedly the approval process for HACS can take multiple months atm)

You may be able to set one up as a custom repository as a bit of a stop gate? Just thinking of ways to get around the long wait time

**Comment by amadeo-alex** [comment]
Yup that's the plan currently, initial idea was to use the original integration as long as possible but looks like it wasn't very long.

Background context:
We've already tried to contact HACS team with the issue - "Sam is MIA, we might need to update the integration, is there a process to get the integration removed/replaced if it's abandoned" - the answer was "not our problem, create a new integration" :D

From the security perspective I understand that, however from the user context it's going to be confusing - there are already 3 HASS.Agent integrations (2 old ones where notification and media player are separate and 1 new all-in-one) - we might need to call the integration "HASS.Agent Integration 2" so it's at least somewhat clear

**Comment by amadeo-alex** [comment]
Notes/context: (I'll update the comment with additional links if found)
https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238

**Comment by Protoncek** [comment]
You're an angel!, amadeo-alex! It works! 
I was pretty frustrated what to do now, since i use my two windows laptops for messages, and since browser-mod's media player never worked for me this was my only solution! I already started to work on additional esphome speaker...

Regarding naming: perhaps you should choose totally another way, say windows HA agent, or similar...?

**Comment by Wank-ster** [comment]
> I can confirm that the workaround also works for people that have never used Hass.agent before 2024.05. device is auto detected as it should and entity notify.device is also created automatically.

Ok unfortunately I need to do one addition:
After successfully adding one device I wanted to add another one and it doesn't show up in autodiscovery. I can restarted HA as well as the PC several times and also un-/installed HASS.agent on the PC. It wont show up. It is listed in MQTT but it won't show up in HA. Any thoughts?

![image](https://github.com/hass-agent/HASS.Agent/assets/142676146/ad1fb6a2-0f96-4603-aaea-69fe2562660f)

**Comment by broyuken** [comment]
I put in the workaround and was able to get my notifications and media player working again

**Comment by phatrickk** [comment]
Ok, I've entered the info in the work around, but now having more signficant issues. What am I doing wrong?

After adjusting init.py (mine's called '__init__.py') follolwing the instructions and then restarting HASS, I immediately get an error on boot saying that hass-agent could not be set up. And the logs look like this:

![image](https://github.com/hass-agent/HASS.Agent/assets/125029396/32eb31e9-23d7-4307-95fd-1b93b7a43d11)

Any idea what's up? For what it's worth, I juts found this fork but am still running the old HASS.Agent software on my windows pc. I imagine that's not the problem though. And just for info, is there documentation about the process for best installing new fork software if you've had the old one installed already? Couldn't find anything.

**Comment by hacshacdgacs** [comment]
> EDIT: Ok, looks like I had my spacing/tabbing slightly off. It seems to start up ok now, but I still don't have notifications back for HASS.Agent. Now I assume it's a software issue. Any documentation on how to update the software for this fork if I have the old one installed?
> 
> Ok, I've entered the info in the work around, but now having more signficant issues. What am I doing wrong?
> 
> After adjusting init.py (mine's called "**init**.py" --- with two underscores either side of init, which wont show) follolwing the instructions and then restarting HASS, I immediately get an error on boot saying that hass-agent could not be set up. And the logs look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/125029396/327595472-32eb31e9-23d7-4307-95fd-1b93b7a43d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MDExNTcsIm5iZiI6MTcxNDcwMDg1NywicGF0aCI6Ii8xMjUwMjkzOTYvMzI3NTk1NDcyLTMyZWIzMWU5LTIzZDctNDMwNy05NWZkLTFiOTNiN2E0M2QxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwMTQ3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzcwMTdhODU0YmE0MjU1OGQ3ZjE1OWVmNmM1ODBjNDkyNzIxYjg1NGQ2N2Y5ZTZlODA2MjA5YTYyY2VjZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rVkUMqJ48ATU9lKWXlD7nvGc-kpGWUOJQKWa8pbdtnY)
> 
> Any idea what's up? For what it's worth, I juts found this fork but am still running the old HASS.Agent software on my windows pc. I imagine that's not the problem though. And just for info, is there documentation about the process for best installing new fork software if you've had the old one installed already? Couldn't find anything.

Just install over the old one and click the option to migrate settings. That's what I did the other day and it works fine

**Comment by phatrickk** [comment]
Ok, I've installed the new software, thanks for advice from above.

But looks like my notify entities aren't being created. Not sure where I should be looking for these, but I'm unable to select my windows computer via the notify service. Any ideas?

**Comment by amadeo-alex** [comment]
@phatrickk so to reiterate:
1. you've modified the init.py file
2. Home Assistant can be rebooted after the modifications and there are no error related to HASS.Agent integration
3. HASS.Agent (forked version) is running (and the original LAB02 version is not) on some device
4. There are still no media player / notification entities on Home Assistant side

Is that correct?

**Comment by phatrickk** [comment]
Nope, false alarm, it's all working now as per those instructions. Thank you very much for everything!

**Comment by RJ-Make** [comment]
Unfortunately, I'm running into loading issues. 

I've:
1) Modified __init__.py file
2) Restarted HA
3) Installed Beta version of Fork.
4) Confirmed there is no old version running. 
5) Restart HA several times. 

I'm sure I've messed something up.

![Snag_18c32644](https://github.com/hass-agent/HASS.Agent/assets/8496835/044f213c-e16f-440e-a99c-873903105303)

```
"""The HASS.Agent integration."""
from __future__ import annotations
import json
import logging
import requests
from .views import MediaPlayerThumbnailView
from homeassistant.helpers import device_registry as dr
from homeassistant.components.mqtt.models import ReceiveMessage
from homeassistant.components.mqtt.subscription import (
    async_prepare_subscribe_topics,
    async_subscribe_topics,
    async_unsubscribe_topics,
)

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_ID, CONF_NAME, CONF_URL, Platform
from homeassistant.core import HomeAssistant
from homeassistant.helpers import discovery

from .const import DOMAIN

PLATFORMS: list[Platform] = [Platform.MEDIA_PLAYER]

_logger = logging.getLogger(__name__)


async def update_device_info(hass: HomeAssistant, entry: ConfigEntry, new_device_info):
    device_registry = dr.async_get(hass)
    device_registry.async_get_or_create(
        config_entry_id=entry.entry_id,
        identifiers={(DOMAIN, entry.unique_id)},
        name=new_device_info["device"]["name"],
        manufacturer=new_device_info["device"]["manufacturer"],
        model=new_device_info["device"]["model"],
        sw_version=new_device_info["device"]["sw_version"],
    )


async def handle_apis_changed(hass: HomeAssistant, entry: ConfigEntry, apis):
    if apis is not None:

        device_registry = dr.async_get(hass)
        device = device_registry.async_get_device(
            identifiers={(DOMAIN, entry.unique_id)}
        )

        media_player = apis.get("media_player", False)
        is_media_player_loaded = hass.data[DOMAIN][entry.entry_id]["loaded"][
            "media_player"
        ]

        notifications = apis.get("notifications", False)

        is_notifications_loaded = hass.data[DOMAIN][entry.entry_id]["loaded"][
            "notifications"
        ]

        if media_player and is_media_player_loaded is False:
            _logger.debug("loading media_player for device: %s", device.name)
            await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

            hass.data[DOMAIN][entry.entry_id]["loaded"]["media_player"] = True
        else:
            if is_media_player_loaded:
                _logger.debug(
                    "unloading media_player for device: %s",
                    device.name,
                )
                await hass.config_entries.async_forward_entry_unload(
                    entry, Platform.MEDIA_PLAYER
                )

                hass.data[DOMAIN][entry.entry_id]["loaded"]["media_player"] = False

        if notifications and is_notifications_loaded is False:
            _logger.debug("loading notify for device: %s", device.name)

            hass.async_create_task(
                discovery.async_load_platform(
                    hass,
                    Platform.NOTIFY,
                    DOMAIN,
                    {CONF_ID: entry.entry_id, CONF_NAME: device.name},
                    {},
                )
            )
            hass.data[DOMAIN][entry.entry_id]["loaded"]["notifications"] = True
        else:
            if is_notifications_loaded:
                _logger.debug("unloading notify for device: %s", device.name)
                await hass.config_entries.async_unload_platforms(
                    entry, [Platform.NOTIFY]
                )

                hass.data[DOMAIN][entry.entry_id]["loaded"]["notifications"] = False


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up HASS.Agent from a config entry."""

    hass.data.setdefault(DOMAIN, {})

    hass.data[DOMAIN].setdefault(
        entry.entry_id,
        {
            "internal_mqtt": {},
            "apis": {},
            "thumbnail": None,
            "loaded": {"media_player": False, "notifications": False},
        },
    )

    url = entry.data.get(CONF_URL, None)

    if url is not None:

        def get_device_info():
            return requests.get(f"{url}/info", timeout=10)

        response = await hass.async_add_executor_job(get_device_info)

        response_json = response.json()

        update_device_info(hass, entry, response_json)

        apis = {
            "notifications": True,
            "media_player": False,  # unsupported for the moment
        }

        hass.async_create_task(handle_apis_changed(hass, entry, apis))
        hass.data[DOMAIN][entry.entry_id]["apis"] = apis

    else:
        device_name = entry.data["device"]["name"]

        sub_state = hass.data[DOMAIN][entry.entry_id]["internal_mqtt"]

		async def updated(message: ReceiveMessage):
            payload = json.loads(message.payload)
            cached = hass.data[DOMAIN][entry.entry_id]["apis"]
            apis = payload["apis"]

            await update_device_info(hass, entry, payload)

            if cached != apis:
                hass.async_create_task(handle_apis_changed(hass, entry, apis))
                hass.data[DOMAIN][entry.entry_id]["apis"] = apis

        sub_state = async_prepare_subscribe_topics(
            hass,
            sub_state,
            {
                f"{entry.unique_id}-apis": {
                    "topic": f"hass.agent/devices/{device_name}",
                    "msg_callback": updated,
                    "qos": 0,
                }
            },
        )

        await async_subscribe_topics(hass, sub_state)

        hass.data[DOMAIN][entry.entry_id]["internal_mqtt"] = sub_state

    return True
```

**Comment by amadeo-alex** [comment]
@RJ-Make Python cannot into tabs :D (I mean tabs as a '\t' character)
In line 139 you have 2 tabs instead of 8 spaces (1tab=4spaces)
Instead of this:
```
		async def updated(message: ReceiveMessage):
```
you need this:
```
        async def updated(message: ReceiveMessage):
```

**Comment by RJ-Make** [comment]
@amadeo-alex Thank you very much for all your help. I'm so glad you gave me the correct string, because I even screwed up the manual correction. ;-( 

Copying and pasting your string worked perfectly. 

Thanks Again!!

**Comment by Failure404** [comment]
I think line 124 also needs an 'await':

    await update_device_info(hass, entry, response_json)

**Comment by amadeo-alex** [comment]
> I think line 124 also needs an 'await':
> 
> ```
> await update_device_info(hass, entry, response_json)
> ```

thank you, updated my original comment

**Comment by amadeo-alex** [comment]
The update needs to happen "on our" (fork's) side - the original integration in HACS was added by Sam (original author of HASS.Agent), this means we cannot do anything about it. We need to get the changes done in out fork and then do a small instruction on how to add it as a custom HACS repository*.
I'd like to have it done in a few days however can't make any promises.

*why custom HACS repository - the approval persiod for HACS (so that given integration is listed without adding a custom repository) is quite long

**Comment by broyuken** [comment]
Either that or we add a PR that Sam would need to approve and merge.

**Comment by amadeo-alex** [comment]
True, problem is that Sam is MIA for quite a long time - that's why the fork started.

**Comment by amadeo-alex** [comment]
LAB02-Research = Sam = original
There might be some more history behind this however when me and @DrR0X-glitch got our focus on HASS.Agent, only Sam was semi-responsive, from what we know some life-stuff consumed their whole attention.

hass-agent/HASS.Agent = "HASS.Agent Organization" = fork
Was started by me and @DrR0X-glitch as an attempt to keep the project alive until Sam is back at which point we can either merge what we've added or just back-port the work to the original repo.
It started as me contacting Sam in regards to the "help neeed" post they created - I started to fix bugs and create PRs to the original repository. After a few emails however the contact got completely lost and there has been nothing since then - I still have hope that at some point Sam will be back however we do not have any guarantee on that.

The main mission-focus for now is to fix bugs as they go and implement new features if they don't require major redesign of existing code. Side focus goes to what I like to call HASS.Agent 3.X which is complete rewrite in WinUI3 and without K.I.S.S principle that should make additions/expansions to HASS.Agent a lot easier - no timelines and/or promises on that tho.

**Comment by Scoff123** [comment]
Can I just check the process to migrate from the original HASS.Agent to this fork please?
1) Download latest windows installer from fork repo
2) Install over the top of original HASS.Agent, and tick the checkbox to Migrate settings during install
3) Reboot Windows device
4) Add fork repo URL as a custom repo in Home Assistant HACS Integrations
5) Download fork integration in HACS
6) Make file edits to init.py as per the above
7) Restart HA 

Is that correct?

**Comment by NowanIlfideme** [comment]
@Scoff123 That's what I did, except I didn't have the old integration. Probably you'll need to uninstall the old one from HACS.

One issue is that it still shows @LAB02-Research as the main author... which is correct, but it looks like you're using the wrong integration, even if the org is fixed.

**Comment by TonyOneZero** [comment]
@amadeo-alex Can you already say when you will publish a fixed version on https://github.com/hass-agent/HASS.Agent? So that you don't have to do this editing manually?

**Comment by amadeo-alex** [comment]
> @amadeo-alex Can you already say when you will publish a fixed version on https://github.com/hass-agent/HASS.Agent? So that you don't have to do this editing manually?

I'd like to have the code ready (not only this fix but also others from the PRs) and prepared as a custom HACS repository (getting into official HACS repositories will take us some time) this weekend - working on it as we speak.

**Comment by TonyOneZero** [comment]
That sounds very good. Thanks for keeping it alive and thanks for the effort you are putting into the project.

**Comment by TonyOneZero** [comment]
> > @amadeo-alex Can you already say when you will publish a fixed version on https://github.com/hass-agent/HASS.Agent? So that you don't have to do this editing manually?
> 
> I'd like to have the code ready (not only this fix but also others from the PRs) and prepared as a custom HACS repository (getting into official HACS repositories will take us some time) this weekend - working on it as we speak.

That sounds very good. Thanks for keeping it alive and thanks for the effort you are putting into the project.

**Comment by NODeeJay** [comment]
> @Scoff123 That's what I did, except I didn't have the old integration. Probably you'll need to uninstall the old one from HACS.
> 
> One issue is that it still shows @LAB02-Research as the main author... which is correct, but it looks like you're using the wrong integration, even if the org is fixed.

Is the fork for the integration you mention this one: https://github.com/nguilbault/HASS.Agent-Integration/tree/main/custom_components/hass_agent
I see commits from amadeo-alex which makes me assume it could be the right one?

**Comment by amadeo-alex** [comment]
> > @Scoff123 That's what I did, except I didn't have the old integration. Probably you'll need to uninstall the old one from HACS.
> > One issue is that it still shows @LAB02-Research as the main author... which is correct, but it looks like you're using the wrong integration, even if the org is fixed.
> 
> Is the fork for the integration you mention this one: https://github.com/nguilbault/HASS.Agent-Integration/tree/main/custom_components/hass_agent I see commits from amadeo-alex which makes me assume it could be the right one?

Not exactly, it has the PRs/changes but not only mine but someone else's also - someone merged more than one thing, from what I saw quickly, should work but I can't reliably say "use it" :D
Our one will be done today (at least fix for the notifications/media player) and I'll link it here - I'd say that max ETA is 3h from now.

**Comment by amadeo-alex** [comment]
So, it's not all I wanted to have with this version but making it actually work and be easy to install for people is more important.
New (forked) version of the integration can be found here - https://github.com/hass-agent/HASS.Agent-Integration
Needs to be added as a custom repository to HACS, easy to do, instructions are included in the readme - https://github.com/hass-agent/HASS.Agent-Integration?tab=readme-ov-file#installation

I'm actually running it on my live Home Assistant instance. It has been tagged "2.1.0-beta1" but the "beta1" part can be ignored, done that just to make it fit the HASS.Agent client version :)
